services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: covit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
      - ./shared:/shared
    ports:
      - "5432:5432"
    networks:
      - app_network
    # restart: unless-stopped

  backend:
    image: node:23-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./shared:/shared
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/covit
      NODE_ENV: development
    networks:
      - app_network
    # restart: unless-stopped

  frontend:
    image: node:23-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./shared:/shared
    command: sh -c "npm install && npm start"
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - app_network
    # restart: unless-stopped

  grafana:
    image: grafana/grafana:main
    container_name: grafana
    user: "${UID}:${GID}"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./shared:/shared
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - "3001:3000"
    networks:
      - app_network
    # restart: unless-stopped

volumes:
  grafana-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./grafana-data

networks:
  app_network:
    driver: bridge