services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: covit
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres.sh:/docker-entrypoint.sh
      - common_data:/common
    ports:
      - "5432:5432"
    networks:
      - app_network
    entrypoint: ["/docker-entrypoint.sh"]
    restart: unless-stopped

  backend:
    image: node:23-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - common_data:/common
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/covit
      NODE_ENV: development
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    image: node:23-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - common_data:/common
    command: sh -c "npm install && npm start"
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:main
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - common_data:/common
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    networks:
      - app_network
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:
  common_data:

networks:
  app_network:
    driver: bridge